# This is a config for E2B sandbox template.
# You can use template ID (t17n6duf3p68x33j98x4) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("t17n6duf3p68x33j98x4") # Sync sandbox
# sandbox = await AsyncSandbox.create("t17n6duf3p68x33j98x4") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('t17n6duf3p68x33j98x4')

team_id = "4a5ceb0a-57a5-4828-a334-cb10f55eca36"
start_cmd = "/root/.jupyter/start-up.sh"
dockerfile = "e2b.Dockerfile"
template_id = "t17n6duf3p68x33j98x4"
