// Code generated by wunderctl. DO NOT EDIT.

import type { ClientOperationErrors, GraphQLError } from "@wundergraph/sdk/client";

export type OperationErrors = {
	MyNewsletterStatus: MyNewsletterStatusErrors;
	NewsletterToggle: NewsletterToggleErrors;
	askClaude: AskClaudeErrors;
	calculateCID: CalculateCIDErrors;
	createInvite: CreateInviteErrors;
	getAuditLogs: GetAuditLogsErrors;
	getUserCapabilities: GetUserCapabilitiesErrors;
	getUserStats: GetUserStatsErrors;
	getUsers: GetUsersErrors;
	insertDB: InsertDBErrors;
	insertObject: InsertObjectErrors;
	manageCapabilities: ManageCapabilitiesErrors;
	polarListProducts: PolarListProductsErrors;
	queryComposer: QueryComposerErrors;
	queryDB: QueryDBErrors;
	queryLeaderboard: QueryLeaderboardErrors;
	queryMails: QueryMailsErrors;
	queryMe: QueryMeErrors;
	queryUserStats: QueryUserStatsErrors;
	saveMailWIP: SaveMailWIPErrors;
	sendMail: SendMailErrors;
	sendMailWIP: SendMailWIPErrors;
	toggleOnboarded: ToggleOnboardedErrors;
	transcribeAudio: TranscribeAudioErrors;
	updateMe: UpdateMeErrors;
};

export type MyNewsletterStatusErrors = ClientOperationErrors;
export type NewsletterToggleErrors = ClientOperationErrors;
export type AskClaudeErrors = ClientOperationErrors;
export type CalculateCIDErrors = ClientOperationErrors;
export type CreateInviteErrors = ClientOperationErrors;
export type GetAuditLogsErrors = ClientOperationErrors;
export type GetUserCapabilitiesErrors = ClientOperationErrors;
export type GetUserStatsErrors = ClientOperationErrors;
export type GetUsersErrors = ClientOperationErrors;
export type InsertDBErrors = ClientOperationErrors;
export type InsertObjectErrors = ClientOperationErrors;
export type ManageCapabilitiesErrors = ClientOperationErrors;
export type PolarListProductsErrors = ClientOperationErrors;
export type QueryComposerErrors = ClientOperationErrors;
export type QueryDBErrors = ClientOperationErrors;
export type QueryLeaderboardErrors = ClientOperationErrors;
export type QueryMailsErrors = ClientOperationErrors;
export type QueryMeErrors = ClientOperationErrors;
export type QueryUserStatsErrors = ClientOperationErrors;
export type SaveMailWIPErrors = ClientOperationErrors;
export type SendMailErrors = ClientOperationErrors;
export type SendMailWIPErrors = ClientOperationErrors;
export type ToggleOnboardedErrors = ClientOperationErrors;
export type TranscribeAudioErrors = ClientOperationErrors;
export type UpdateMeErrors = ClientOperationErrors;
