// Code generated by wunderctl. DO NOT EDIT.

import type { ClientOperationErrors, GraphQLError } from "@wundergraph/sdk/client";

export type OperationErrors = {
	MyNewsletterStatus: MyNewsletterStatusErrors;
	NewsletterToggle: NewsletterToggleErrors;
	calculateCID: CalculateCIDErrors;
	createInvite: CreateInviteErrors;
	insertDB: InsertDBErrors;
	insertObject: InsertObjectErrors;
	queryComposer: QueryComposerErrors;
	queryDB: QueryDBErrors;
	queryLeaderboard: QueryLeaderboardErrors;
	queryMails: QueryMailsErrors;
	queryMe: QueryMeErrors;
	queryUserStats: QueryUserStatsErrors;
	saveMailWIP: SaveMailWIPErrors;
	sendMail: SendMailErrors;
	sendMailWIP: SendMailWIPErrors;
	updateMe: UpdateMeErrors;
};

export type MyNewsletterStatusErrors = ClientOperationErrors;
export type NewsletterToggleErrors = ClientOperationErrors;
export type CalculateCIDErrors = ClientOperationErrors;
export type CreateInviteErrors = ClientOperationErrors;
export type InsertDBErrors = ClientOperationErrors;
export type InsertObjectErrors = ClientOperationErrors;
export type QueryComposerErrors = ClientOperationErrors;
export type QueryDBErrors = ClientOperationErrors;
export type QueryLeaderboardErrors = ClientOperationErrors;
export type QueryMailsErrors = ClientOperationErrors;
export type QueryMeErrors = ClientOperationErrors;
export type QueryUserStatsErrors = ClientOperationErrors;
export type SaveMailWIPErrors = ClientOperationErrors;
export type SendMailErrors = ClientOperationErrors;
export type SendMailWIPErrors = ClientOperationErrors;
export type UpdateMeErrors = ClientOperationErrors;
