app = 'api-visioncreator-earth'
primary_region = "fra"

[build]

[http_service]
internal_port = 9991
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 1
processes = ['app']

[[services]]
protocol = ''
internal_port = 9991
ports = []

[[vm]]
memory = '2gb'
cpu_kind = 'shared'
cpus = 2
