name: production-api-deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy app (Production)
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - uses: actions/checkout@v3

      - name: Set up Fly
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Generate WunderGraph Secrets
        run: |
          echo "WG_CSRF_TOKEN_SECRET=$(openssl rand -hex 6)" >> $GITHUB_ENV
          echo "WG_SECURE_COOKIE_HASH_KEY=$(openssl rand -hex 32)" >> $GITHUB_ENV
          echo "WG_SECURE_COOKIE_BLOCK_KEY=$(openssl rand -hex 32)" >> $GITHUB_ENV

      - name: Deploy to Fly (Production)
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          cd apps/api

          # Check if the app exists
          if ! flyctl apps list | grep -q "api-visioncreator-earth"; then
            echo "App does not exist. Creating new app..."
            flyctl apps create api-visioncreator-earth
          else
            echo "App already exists. Proceeding with deployment..."
          fi

          # Set secrets
          flyctl secrets set \
            --config fly.production.toml \
            ENV="production" \
            WG_CSRF_TOKEN_SECRET="${{ env.WG_CSRF_TOKEN_SECRET }}" \
            WG_SECURE_COOKIE_HASH_KEY="${{ env.WG_SECURE_COOKIE_HASH_KEY }}" \
            WG_SECURE_COOKIE_BLOCK_KEY="${{ env.WG_SECURE_COOKIE_BLOCK_KEY }}" \
            SUPABASE_URL="${{ secrets.SUPABASE_URL }}" \
            SUPABASE_SERVICE_ROLE="${{ secrets.SUPABASE_SERVICE_ROLE }}" \
            NANGO_SECRET_KEY="${{ secrets.NANGO_SECRET_KEY }}" \
            NANGO_HOST="${{ secrets.NANGO_HOST }}" \
            POSTMARK_SERVER_TOKEN="${{ secrets.POSTMARK_SERVER_TOKEN }}"

          # Deploy the app
          flyctl deploy --config fly.production.toml --remote-only
