name: Supabase Full Backup and Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight

jobs:
  backup:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      DB_HOST: ${{ secrets.SUPABASE_DB_HOST }}
      DB_USER: ${{ secrets.SUPABASE_DB_USER }}
      SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
      DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
      DB_NAME: ${{ secrets.SUPABASE_DB_NAME }}
    steps:
      - uses: actions/checkout@v4

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Install PostgreSQL 15 client and jq
        run: |
          sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
          wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
          sudo apt-get update
          sudo apt-get install -y postgresql-client-15 jq
          sudo update-alternatives --install /usr/bin/pg_dump pg_dump /usr/lib/postgresql/15/bin/pg_dump 1500
          pg_dump --version

      - name: Construct DB URL with encoded password
        run: |
          ENCODED_PASSWORD=$(echo -n "$DB_PASSWORD" | jq -sRr @uri)
          DB_URL="postgresql://$DB_USER.$SUPABASE_PROJECT_ID:$ENCODED_PASSWORD@$DB_HOST:5432/$DB_NAME"
          echo "DB_URL=$DB_URL" >> $GITHUB_ENV

      - name: Set backup filename
        run: |
          TIMESTAMP=$(date +'%Y-%m-%d_%H-%M-%S')
          if [[ "${{ github.event_name }}" == "schedule" ]]; then
            BACKUP_FILENAME="${TIMESTAMP}_cronjob.dump"
          else
            SHORT_SHA=$(git rev-parse --short HEAD)
            BACKUP_FILENAME="${TIMESTAMP}_${SHORT_SHA}_commit.dump"
          fi
          echo "BACKUP_FILENAME=$BACKUP_FILENAME" >> $GITHUB_ENV

      - name: Backup entire database (including auth)
        run: |
          /usr/lib/postgresql/15/bin/pg_dump "$DB_URL" -F c -f ${{ env.BACKUP_FILENAME }}

      - name: Upload full backup to DO Spaces
        uses: BetaHuhn/do-spaces-action@v2
        with:
          access_key: ${{ secrets.DO_ACCESS_KEY }}
          secret_key: ${{ secrets.DO_SECRET_KEY }}
          space_name: ${{ secrets.DO_SPACE_NAME }}
          space_region: ${{ secrets.DO_SPACE_REGION }}
          source: ${{ env.BACKUP_FILENAME }}
          out_dir: /

      - name: Clean up local backup files
        run: rm ${{ env.BACKUP_FILENAME }}

  deploy:
    needs: backup
    runs-on: ubuntu-latest
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
      PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Supabase Login
        run: supabase login $SUPABASE_ACCESS_TOKEN

      - name: Deploy Supabase Migration
        run: |
          cd packages/supacreator/supabase
          supabase link --project-ref $PROJECT_ID
          supabase db push
