name: Deploy Supabase Changes

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
      PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
      DO_SPACE_NAME: ${{ secrets.DO_SPACE_NAME }}
      DO_ACCESS_KEY: ${{ secrets.DO_ACCESS_KEY }}
      DO_SECRET_KEY: ${{ secrets.DO_SECRET_KEY }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Install s3cmd
        run: sudo apt-get install s3cmd

      - name: Supabase Login
        run: supabase login $SUPABASE_ACCESS_TOKEN

      - name: Dump Supabase Database
        run: |
          cd packages/supacreator/supabase
          supabase link --project-ref $PROJECT_ID
          TIMESTAMP=$(date +%Y%m%d_%H%M%S)
          supabase db dump -f supabase_dump_$TIMESTAMP.sql

      - name: Upload Dump to Digital Ocean Space
        run: |
          s3cmd --access_key=$DO_ACCESS_KEY --secret_key=$DO_SECRET_KEY --host=$DO_SPACE_REGION.digitaloceanspaces.com --host-bucket="%(bucket)s.$DO_SPACE_REGION.digitaloceanspaces.com" put packages/supacreator/supabase/supabase_dump_*.sql s3://$DO_SPACE_NAME/supabase_backups/

      - name: Deploy Supabase Migration
        run: |
          cd packages/supacreator/supabase
          supabase db push
