name: Supabase Full Backup

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight

jobs:
  run_db_backup:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      DB_HOST: ${{ secrets.SUPABASE_DB_HOST }}
      DB_USER: ${{ secrets.SUPABASE_DB_USER }}
      DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
      DB_NAME: ${{ secrets.SUPABASE_DB_NAME }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Backup schema and roles
        run: |
          supabase db dump "postgresql://$DB_USER:$DB_PASSWORD@$DB_HOST:5432/$DB_NAME" -f schema_backup.sql

      - name: Backup data
        run: |
          supabase db dump "postgresql://$DB_USER:$DB_PASSWORD@$DB_HOST:5432/$DB_NAME" -f data_backup.sql --data-only --use-copy

      - name: Upload schema backup to DO Spaces
        uses: BetaHuhn/do-spaces-action@v2
        with:
          access_key: ${{ secrets.DO_ACCESS_KEY }}
          secret_key: ${{ secrets.DO_SECRET_KEY }}
          space_name: ${{ secrets.DO_SPACE_NAME }}
          space_region: ${{ secrets.DO_SPACE_REGION }}
          source: schema_backup.sql
          out_dir: supabase_backups/$(date +%Y-%m-%d)

      - name: Upload data backup to DO Spaces
        uses: BetaHuhn/do-spaces-action@v2
        with:
          access_key: ${{ secrets.DO_ACCESS_KEY }}
          secret_key: ${{ secrets.DO_SECRET_KEY }}
          space_name: ${{ secrets.DO_SPACE_NAME }}
          space_region: ${{ secrets.DO_SPACE_REGION }}
          source: data_backup.sql
          out_dir: supabase_backups/$(date +%Y-%m-%d)

      - name: Clean up local backup files
        run: |
          rm schema_backup.sql data_backup.sql
