name: Supabase Full Backup and Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight

jobs:
  backup:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
      SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
    steps:
      - uses: actions/checkout@v4

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Supabase Login
        run: supabase login $SUPABASE_ACCESS_TOKEN

      - name: Create minimal Supabase config
        run: |
          mkdir -p supabase
          echo "project_id = \"$SUPABASE_PROJECT_ID\"" > supabase/config.toml

      - name: Link to Supabase project
        run: supabase link --project-ref $SUPABASE_PROJECT_ID

      - name: Set backup prefix
        run: |
          TIMESTAMP=$(date +'%Y-%m-%d_%H-%M-%S')
          if [[ "${{ github.event_name }}" == "schedule" ]]; then
            BACKUP_PREFIX="${TIMESTAMP}_cronjob"
          else
            SHORT_SHA=$(git rev-parse --short HEAD)
            BACKUP_PREFIX="${TIMESTAMP}_${SHORT_SHA}_commit"
          fi
          echo "BACKUP_PREFIX=$BACKUP_PREFIX" >> $GITHUB_ENV

      - name: Create backup folder
        run: mkdir -p ${{ env.BACKUP_PREFIX }}

      - name: Backup roles
        run: supabase db dump -f ${{ env.BACKUP_PREFIX }}/${{ env.BACKUP_PREFIX }}_roles.sql --role-only

      - name: Backup schema
        run: supabase db dump -f ${{ env.BACKUP_PREFIX }}/${{ env.BACKUP_PREFIX }}_schema.sql

      - name: Backup data
        run: supabase db dump -f ${{ env.BACKUP_PREFIX }}/${{ env.BACKUP_PREFIX }}_data.sql --data-only --use-copy

      - name: Backup migration history
        run: supabase db dump -f ${{ env.BACKUP_PREFIX }}/${{ env.BACKUP_PREFIX }}_migrations.sql --schema supabase_migrations

      - name: Upload backup folder to DO Spaces
        uses: BetaHuhn/do-spaces-action@v2
        with:
          access_key: ${{ secrets.DO_ACCESS_KEY }}
          secret_key: ${{ secrets.DO_SECRET_KEY }}
          space_name: ${{ secrets.DO_SPACE_NAME }}
          space_region: ${{ secrets.DO_SPACE_REGION }}
          source: ${{ env.BACKUP_PREFIX }}
          out_dir: ${{ env.BACKUP_PREFIX }}

      - name: Clean up local backup folder
        run: rm -rf ${{ env.BACKUP_PREFIX }}

  deploy:
    needs: backup
    runs-on: ubuntu-latest
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
      PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Supabase Login
        run: supabase login $SUPABASE_ACCESS_TOKEN

      - name: Deploy Supabase Migration
        run: |
          cd packages/supacreator/supabase
          supabase link --project-ref $PROJECT_ID
          supabase db push
