name: Deploy Wundergraph Changes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Fly
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Generate WunderGraph Secrets
        run: |
          echo "WG_CSRF_TOKEN_SECRET=$(openssl rand -hex 6)" >> $GITHUB_ENV
          echo "WG_SECURE_COOKIE_HASH_KEY=$(openssl rand -hex 32)" >> $GITHUB_ENV
          echo "WG_SECURE_COOKIE_BLOCK_KEY=$(openssl rand -hex 32)" >> $GITHUB_ENV

      - name: Deploy to Fly
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          cd visioncreator/apps/api
          flyctl secrets set \
            WG_CSRF_TOKEN_SECRET="${{ env.WG_CSRF_TOKEN_SECRET }}" \
            WG_SECURE_COOKIE_HASH_KEY="${{ env.WG_SECURE_COOKIE_HASH_KEY }}" \
            WG_SECURE_COOKIE_BLOCK_KEY="${{ env.WG_SECURE_COOKIE_BLOCK_KEY }}" \
            SUPABASE_URL="${{ secrets.SUPABASE_URL }}" \
            SUPABASE_SERVICE_ROLE="${{ secrets.SUPABASE_SERVICE_ROLE }}" \
            NANGO_SECRET_KEY="${{ secrets.NANGO_SECRET_KEY }}" \
            NANGO_HOST="${{ secrets.NANGO_HOST }}"
          flyctl deploy --remote-only
